export const basic: { [char: string]: string } = {
    "A": "А",
    "a": "а",
    "E": "Е",
    "e": "е",
    "O": "О",
    "o": "о",
    "I": "І",
    "i": "і",
}

export const extended: { [char: string]: string } = {
    ...basic,
    "B": "В",
    "K": "К",
    "M": "М",
    "H": "Н",
    "P": "Р",
    "p": "р",
    "C": "С",
    "c": "с",
    "T": "Т",
    "y": "у",
    "X": "Х",
    "x": "х",
    "V": "Ѵ",
    "v": "ѵ",
    "u": "υ",
    " ": "ﾠ",
}